ASSETS_PATH = "/home/nongtajkrub/Coding/Python/trash-game/assets/"

SKY_IMG_PATH = ASSETS_PATH + "sky.jpg"

HAZARDOUS_IMG_PATH = ASSETS_PATH + "dangerous_bin.png"
RECYCLABLE_IMG_PATH = ASSETS_PATH + "recycle_bin.png"
ORGANIC_IMG_PATH = ASSETS_PATH + "batties_maybe_bin.png"
GENERAL_IMG_PATH = ASSETS_PATH + "general_bin.png"

APPLE_IMG_PATH = ASSETS_PATH + "apple.png"
BANANA_IMG_PATH = ASSETS_PATH + "banana.png"
VEGETABLE_IMG_PATH = ASSETS_PATH + "vegetable.png"

POWER_UP_IMG_PATH = ASSETS_PATH + "powerup.png"
SHIELD_IMG_PATH = ASSETS_PATH + "shield.png"
GRASS_IMG_PATH = ASSETS_PATH + "grass.png"
BATTERY_IMG_PATH = ASSETS_PATH + "battery.png"
ELECTRONIC_IMG_PATH = ASSETS_PATH + "electronic.png"
BLEACH_IMG_PATH = ASSETS_PATH + "bleach.png"

FONT_PATH = ASSETS_PATH + "sugar_fruit.otf"

DEFAULT_PLAYER_VEL = 10
BOOSTED_PLAYER_VEL = 15

DEFAULT_POWER_UP_VEL = 5
POWER_UP_TIME = 5000
POWER_UP_SPAWN_FREQ = 10000

TRASH_SPAWN_FREQ = 300
DEFAULT_TRASH_VEL = 3

MAX_FPS = 60
