SCREEN_DIMENSION = (1280, 720)
SCREEN_WIDTH = SCREEN_DIMENSION[0]
SCREEN_HEIGHT = SCREEN_DIMENSION[1]

ASSETS_PATH = "/home/nongtajkrub/Coding/Python/trash-game/assets/"

HAZARDOUS_IMG_PATH = ASSETS_PATH + "red.png"
RECYCLABLE_IMG_PATH = ASSETS_PATH + "aqua.png"
ORGANIC_IMG_PATH = ASSETS_PATH + "pink.png"
GENERAL_IMG_PATH = ASSETS_PATH + "green.png"
SHIELD_IMG_PATH = ASSETS_PATH + "shield.png"

FONT_PATH = ASSETS_PATH + "sugar_fruit.otf"

DEFAULT_PLAYER_VEL = 10
BOOSTED_PLAYER_VEL = 15
DEFAULT_PLAYER_Y = 600

DEFAULT_POWER_UP_VEL = 5
DEFAULT_POWER_UP_Y = 600
POWER_UP_TIME = 5000
POWER_UP_SPAWN_FREQ = 10000

TRASH_SPAWN_FREQ = 300
DEFAULT_TRASH_VEL = 3

MAX_FPS = 60
