SCREEN_DIMENSION = (1280, 720)
SCREEN_WIDTH = SCREEN_DIMENSION[0]
SCREEN_HEIGHT = SCREEN_DIMENSION[1]

ASSETS_PATH = "/home/nongtajkrub/Coding/Python/trash-game/assets/"
HAZARDOUS_IMG_PATH = ASSETS_PATH + "red.png"
RECYCLABLE_IMG_PATH = ASSETS_PATH + "aqua.png"
ORGANIC_IMG_PATH = ASSETS_PATH + "pink.png"
GENERAL_IMG_PATH = ASSETS_PATH + "green.png"

DEFAULT_PLAYER_VEL = 10
DEFAULT_TRASH_VEL = 3
TRASH_SPAWN_FREQ = 300
MAX_FPS = 60
